FROM apache/airflow:2.10.4-python3.12

USER root
RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*

USER airflow

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY --chown=airflow:root . /opt/airflow/project/
ENV PYTHONPATH="/opt/airflow/project:${PYTHONPATH}"
