# Generated by Django 5.2.11 on 2026-02-21 18:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('RETAIL', 'Retail'), ('COMMERCIAL', 'Commercial')], max_length=20, unique=True)),
                ('external_bank_url', models.CharField(max_length=500)),
                ('sync_interval_minutes', models.IntegerField(default=60)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sync_configurations',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_type', models.CharField(max_length=20)),
                ('batch_id', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('FETCHING', 'Fetching'), ('VALIDATING', 'Validating'), ('NORMALIZING', 'Normalizing'), ('STORING', 'Storing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='STARTED', max_length=20)),
                ('total_credit_rows', models.IntegerField(default=0)),
                ('total_payment_rows', models.IntegerField(default=0)),
                ('valid_credit_rows', models.IntegerField(default=0)),
                ('valid_payment_rows', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_summary', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('api_key_hash', models.CharField(max_length=255)),
                ('api_key_prefix', models.CharField(max_length=8)),
                ('pg_database', models.CharField(max_length=50)),
                ('ch_database', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='ValidationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('file_type', models.CharField(max_length=20)),
                ('field_name', models.CharField(max_length=100)),
                ('error_type', models.CharField(choices=[('REQUIRED', 'Required field missing'), ('TYPE', 'Invalid type'), ('RANGE', 'Out of range'), ('FORMAT', 'Invalid format'), ('VALUE', 'Invalid value'), ('CROSS_REFERENCE', 'Cross-reference error')], max_length=50)),
                ('error_message', models.TextField()),
                ('raw_value', models.TextField(blank=True, null=True)),
                ('sync_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_errors', to='adapter.synclog')),
            ],
            options={
                'db_table': 'validation_errors',
                'indexes': [models.Index(fields=['sync_log'], name='validation__sync_lo_0d2840_idx')],
            },
        ),
    ]
