# Generated by Django 5.2.11 on 2026-02-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adapter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='api_key_prefix',
            field=models.CharField(max_length=16),
        ),
    ]
